[package]
name = "link-shortener-scripts"
version = "0.0.0"
authors = ["Shanto <krshanto2005@gmail.com"]
edition = "2021"

[dependencies]
bcrypt = "0.13.0"
 mongodb = "2.3.1"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
